# Generated by Django 5.0.4 on 2024-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True)),
                ('contact_details', models.TextField()),
                ('address', models.TextField(default='', max_length=150)),
                ('vendor_code', models.CharField(default='', max_length=10)),
                ('on_time_delivery_rate', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fullfillment_rate', models.FloatField()),
            ],
        ),
    ]
